package verwaltungsassistent.web.config;

import reasoning.auth.infrastructure.persistence.UserAccountEntity;
import reasoning.auth.infrastructure.persistence.UserAccountRepository;
import reasoning.common.model.DocumentCategory;
import reasoning.common.model.WorkspacePhase;
import reasoning.common.model.WorkspaceStatus;
import reasoning.document.api.DocumentFacade;
import reasoning.document.api.DocumentFilter;
import reasoning.document.model.Document;
import reasoning.search.infrastructure.persistence.DocumentChunkEntity;
import reasoning.search.infrastructure.persistence.JpaDocumentChunkRepository;
import reasoning.workspace.api.AttachDocumentCommand;
import reasoning.workspace.api.WorkspaceDocumentLinkEntity;
import reasoning.workspace.api.WorkspaceEntity;
import reasoning.workspace.application.WorkspaceService;
import verwaltungsassistent.web.service.DemoDataService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Startup demo-state reset (dev/demo profiles, invoked by {@link DemoCaseSeeder}).
 *
 * <p>Every application start must restore the SAME demo workflow state — the
 * demo is reproducible. This class resets ONLY the workflow state generated by
 * previous demo runs:</p>
 * <ul>
 *   <li>catalog e-mails return to their catalog definition (status, assignment,
 *       no analysis link); stored e-mail analyses are removed;</li>
 *   <li>seeded cases return to their initial phase/status; analysis runs,
 *       analysis markers, checklists, notes and timeline events are removed;
 *       documents are reset to the canonical seeded set;</li>
 *   <li>workspaces created during previous demo runs (e-mail → Vorgang,
 *       leftovers) are removed; duplicate seeded cases are collapsed;</li>
 *   <li>closed demo-user cases (Ummeldung …) receive a deterministic completed
 *       analysis fixture so their Entscheidungsvorlage remains exportable.</li>
 * </ul>
 *
 * <p>Knowledge-base state is NEVER touched: source documents, embeddings and
 * Qdrant/vector data stay intact. The reset is idempotent.</p>
 */
@Component
@Profile({"dev", "demo"})
public class DemoStateResetter {

    private static final Logger log = LoggerFactory.getLogger(DemoStateResetter.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private final WorkspaceService workspaceService;
    private final DocumentFacade documentFacade;
    private final DemoDataService demoDataService;
    private final JpaDocumentChunkRepository chunkRepository;
    private final UserAccountRepository userAccountRepository;
    private final verwaltungsassistent.web.planning.persistence.JpaCasePlanningRepository casePlanningRepository;
    private final verwaltungsassistent.web.planning.persistence.JpaEffortObservationRepository effortObservationRepository;

    /** GreenMail-Demo-Mailbox (Phase 2C.2) — nur im demo-Profil vorhanden. */
    private final verwaltungsassistent.web.mailbox.DemoMailboxSeeder demoMailboxSeeder;

    public DemoStateResetter(WorkspaceService workspaceService,
                             DocumentFacade documentFacade,
                             DemoDataService demoDataService,
                             JpaDocumentChunkRepository chunkRepository,
                             UserAccountRepository userAccountRepository,
                             verwaltungsassistent.web.planning.persistence.JpaCasePlanningRepository casePlanningRepository,
                             verwaltungsassistent.web.planning.persistence.JpaEffortObservationRepository effortObservationRepository,
                             @org.springframework.beans.factory.annotation.Autowired(required = false)
                             verwaltungsassistent.web.mailbox.DemoMailboxSeeder demoMailboxSeeder) {
        this.workspaceService = workspaceService;
        this.documentFacade = documentFacade;
        this.demoDataService = demoDataService;
        this.chunkRepository = chunkRepository;
        this.userAccountRepository = userAccountRepository;
        this.casePlanningRepository = casePlanningRepository;
        this.effortObservationRepository = effortObservationRepository;
        this.demoMailboxSeeder = demoMailboxSeeder;
    }

    /** Canonical corpus documents of the closed demo cases (Ummeldung). */
    private static final List<String> UMMELDUNG_DOCS = List.of(
            "Änderung/Wechsel der Hauptwohnung", "Abmeldung einer Wohnung");

    // ── Entry point ──────────────────────────────────────────────────────────

    /** Runs the complete demo workflow-state reset (idempotent). */
    @Transactional
    public void reset() {
        demoDataService.resetEmailQueue();
        demoDataService.deleteAllEmailAnalyses();
        ensureDemoUserProfiles();
        removeLeftoverWorkspaces();
        resetDemoUserWorkspaces();
        // Abschluss-Szenarien zuletzt: die Erledigt-Katalog-E-Mails erhalten
        // nach der Analyse-Bereinigung wieder ihren Vorgang und ihr
        // deterministisches Vor-Analyse-Ergebnis; danach die voranalysierten
        // Neueingänge (Phase 2C.1, Szenarien A + D).
        demoDataService.seedCompletedScenario();
        demoDataService.seedPreAnalyzedEmails();
        // Phase 2C.2: GreenMail-Demo-Mailbox deterministisch neu befüllen
        // (leeren + gleiche Message-IDs — ein zweiter Reset akkumuliert nichts).
        if (demoMailboxSeeder != null) {
            demoMailboxSeeder.reseed();
        }
        // GEO-Demo-Register-Selbstheilung: Wurde das Register (noch) nicht
        // aufgebaut oder fehlt es (z. B. frischer Datenbank-Stand), wird es
        // deterministisch erzeugt — GEO-only, idempotent, ohne E-Mail-/Fall-
        // Bestand anzufassen. resetDemoUserWorkspaces LÖSCHT Geovorgänge nicht
        // mehr (GEO gehört nicht zum CASE-Ausgangszustand).
        try {
            boolean geoPresent = workspaceService.findAll().stream()
                    .anyMatch(w -> "GEO".equalsIgnoreCase(w.getWorkspaceType()));
            if (!geoPresent) {
                log.info("GEO-Demo-Register fehlt — deterministischer GEO-Aufbau …");
                demoDataService.refreshGeoDemoState();
            }
        } catch (Exception e) {
            log.warn("GEO-Selbstheilung nicht möglich: {}", e.getMessage());
        }
    }

    // ── Demo user profiles (phone etc.) ──────────────────────────────────────

    /** Fills the profile telephone number of existing demo users (PDF BEARBEITET VON, signatures). */
    private void ensureDemoUserProfiles() {
        for (int i = 1; i <= DemoDataService.DEMO_USER_COUNT; i++) {
            final int n = i;
            try {
                String email = String.format("demo%02d", n) + DemoDataService.DEMO_EMAIL_SUFFIX;
                userAccountRepository.findByEmail(email).ifPresent(u -> {
                    if (u.getPhone() == null || u.getPhone().isBlank()) {
                        u.setPhone("0331 289-" + (1000 + n));
                        userAccountRepository.save(u);
                        log.info("Demo-Profil {}: Telefonnummer ergänzt", email);
                    }
                });
            } catch (Exception e) {
                log.debug("Demo-Profil {} nicht aktualisiert: {}", "demo" + n, e.getMessage());
            }
        }
    }

    // ── Leftover / duplicate workspaces ──────────────────────────────────────

    /**
     * Removes workspaces created during previous demo runs: admin-owned
     * non-GEO workspaces that are not part of the seeded set. Duplicates of a
     * seeded case (same normalized name) are collapsed to one case — the
     * non-email-created variant wins (the seeded one), the others are removed.
     */
    @Transactional
    public void removeLeftoverWorkspaces() {
        Set<String> seededNames = new java.util.HashSet<>(DemoCaseSeeder.SEEDED_CASE_NAMES);
        seededNames.addAll(DemoDataService.COMPLETED_CASE_NAMES.stream()
                .map(n -> normalizeName(n)).toList());
        List<WorkspaceEntity> all = new ArrayList<>(workspaceService.findAll());
        // Gruppe nach normalisiertem Namen: nur ein Fall pro Name darf bleiben.
        Map<String, List<WorkspaceEntity>> byName = all.stream()
                .filter(ws -> "CASE".equalsIgnoreCase(ws.getWorkspaceType()))
                .collect(Collectors.groupingBy(ws -> normalizeName(ws.getName())));
        for (Map.Entry<String, List<WorkspaceEntity>> entry : byName.entrySet()) {
            if (!seededNames.contains(entry.getKey())) {
                continue;
            }
            List<WorkspaceEntity> group = entry.getValue();
            if (group.size() <= 1) {
                continue;
            }
            WorkspaceEntity keeper = pickSeededVariant(group);
            for (WorkspaceEntity ws : group) {
                if (!ws.getId().equals(keeper.getId())) {
                    log.info("Entferne Duplikat des Demo-Falls '{}' ({})", ws.getName(), ws.getId());
                    deleteWorkspace(ws);
                }
            }
        }
        // Übrig gebliebene Admin-Fälle aus früheren Demo-Läufen (E-Mail → Vorgang …).
        for (WorkspaceEntity ws : all) {
            if ("GEO".equalsIgnoreCase(ws.getWorkspaceType())) {
                continue;
            }
            if (!DemoDataService.DEMO_OWNER.equals(ws.getOwnerId())) {
                continue;
            }
            if (seededNames.contains(normalizeName(ws.getName()))) {
                continue;
            }
            log.info("Entferne Alt-Demo-Fall '{}' (nicht Teil des Demo-Ausgangszustands)", ws.getName());
            deleteWorkspace(ws);
        }
        // Phase 2C.3b: automatisch angelegte Mailbox-Intake-Vorgänge (bewusst
        // NICHT zugewiesen, owner null) gehören nicht zum Demo-Ausgangszustand —
        // die GreenMail-Mailbox wird danach neu befüllt und der nächste Abruf
        // legt sie mit identischem Aktenzeichen neu an (deterministisch).
        for (WorkspaceEntity ws : all) {
            if (!"CASE".equalsIgnoreCase(ws.getWorkspaceType())) {
                continue;
            }
            if (ws.getOwnerId() != null) {
                continue;
            }
            if (!isMailboxIntakeCase(ws)) {
                continue;
            }
            log.info("Entferne Mailbox-Intake-Vorgang '{}' ({}) — Neuaufbau beim nächsten Abruf",
                    ws.getName(), ws.getWorkspaceCode());
            deleteWorkspace(ws);
        }
    }

    /** Intake-Marker aus dem automatischen Mailbox-Intake (Phase 2C.3b). */
    private static boolean isMailboxIntakeCase(WorkspaceEntity ws) {
        try {
            return ws.getPhaseData() != null
                    && ws.getPhaseData().contains("\"intakeSource\":\"MAILBOX\"");
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * The variant that keeps the seeded state: a case whose source is a seeded
     * demo e-mail beats an e-mail-created case; among equals the one with the
     * most documents (canonical attachments) wins; last resort: oldest.
     */
    private WorkspaceEntity pickSeededVariant(List<WorkspaceEntity> group) {
        List<WorkspaceEntity> sorted = new ArrayList<>(group);
        sorted.sort((a, b) -> {
            boolean aEmail = isEmailCreated(a);
            boolean bEmail = isEmailCreated(b);
            if (aEmail != bEmail) return aEmail ? 1 : -1;
            int aDocs = docCount(a);
            int bDocs = docCount(b);
            if (aDocs != bDocs) return Integer.compare(bDocs, aDocs);
            return a.getCreatedAt() == null ? 1
                    : (b.getCreatedAt() == null ? -1
                    : a.getCreatedAt().compareTo(b.getCreatedAt()));
        });
        return sorted.get(0);
    }

    private boolean isEmailCreated(WorkspaceEntity ws) {
        try {
            return ws.getPhaseData() != null && ws.getPhaseData().contains("sourceEmailId");
        } catch (Exception e) {
            return false;
        }
    }

    private int docCount(WorkspaceEntity ws) {
        try {
            return workspaceService.getWorkspaceDocuments(ws.getId().toString()).size();
        } catch (Exception e) {
            return 0;
        }
    }

    private void deleteWorkspace(WorkspaceEntity ws) {
        try {
            workspaceService.deleteWorkspace(ws.getId().toString());
            // Planungsstände und Beobachtungen gelöschter Fälle nicht verwaist zurücklassen.
            casePlanningRepository.deleteByCaseId(java.util.UUID.fromString(ws.getId()));
            effortObservationRepository.deleteByCaseId(java.util.UUID.fromString(ws.getId()));
        } catch (Exception e) {
            log.warn("Workspace-Bereinigung fehlgeschlagen: {} ({})", ws.getName(), e.getMessage());
        }
    }

    // ── Demo-user workspaces (createDemoCase state) ──────────────────────────

    /**
     * Resets every demo-user workspace to its seeded {@code createDemoCase}
     * state: Wohngeldantrag → ACTIVE/REVIEW, Ummeldung → CLOSED/COMPLETE with a
     * deterministic completed analysis (exportable Entscheidungsvorlage).
     * Workspaces that match neither seeded shape are removed (leftovers).
     */
    @Transactional
    public void resetDemoUserWorkspaces() {
        List<WorkspaceEntity> all = new ArrayList<>(workspaceService.findAll());
        for (WorkspaceEntity ws : all) {
            // Geovorgänge gehören NICHT zum CASE-Ausgangszustand: Sie werden
            // vom GEO-Demo-Register verwaltet (refreshGeoDemoState) und dürfen
            // vom Boot-Reset weder gelöscht noch zurückgesetzt werden — sonst
            // zeigt die Geovorgänge-Seite leer und Foto-Links ins Leere.
            if ("GEO".equalsIgnoreCase(ws.getWorkspaceType())) {
                continue;
            }
            String owner = ws.getOwnerId();
            if (owner == null || !(owner.startsWith("demo") && owner.endsWith(DemoDataService.DEMO_EMAIL_SUFFIX))) {
                continue;
            }
            String name = ws.getName() != null ? ws.getName() : "";
            if (name.contains("Wohngeldantrag")) {
                resetToSeedState(ws, WorkspaceStatus.ACTIVE, WorkspacePhase.REVIEW);
            } else if (name.contains("Ummeldung")) {
                resetToSeedState(ws, WorkspaceStatus.CLOSED, WorkspacePhase.COMPLETE);
                seedClosedCaseAnalysis(ws);
            } else {
                log.info("Entferne Demo-Benutzer-Fall '{}' (kein Teil des Demo-Ausgangszustands)", name);
                deleteWorkspace(ws);
            }
        }
    }

    /** Wipes workflow-generated state and restores the seeded phase/status/phaseData. */
    private void resetToSeedState(WorkspaceEntity ws, WorkspaceStatus status, WorkspacePhase phase) {
        try {
            workspaceService.deleteAnalysisRuns(ws.getId().toString());
            workspaceService.replaceTimeline(ws.getId().toString(), List.of());
        } catch (Exception e) {
            log.warn("Ableitete Daten von '{}' nicht vollständig zurückgesetzt: {}", ws.getName(), e.getMessage());
        }
        ws.setStatus(status);
        ws.setPhase(phase);
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("demo", true);
        String citizen = ownerDisplayName(ws.getOwnerId());
        data.put("citizen", citizen != null ? citizen : ws.getOwnerId());
        // Auslöser konsistent zum Seed-Zustand: Bürger-E-Mail vor der Anlage.
        if (ws.getCreatedAt() != null) {
            data.put("source", "E-Mail vom " + verwaltungsassistent.web.util.DateTimeFormats
                    .formatInstant(ws.getCreatedAt().minus(java.time.Duration.ofDays(1)), null));
        }
        ws.setPhaseData(toJson(data));
        workspaceService.save(ws);
        log.info("Demo-Fall '{}' auf Ausgangszustand zurückgesetzt ({}/{})", ws.getName(), status, phase);
    }

    private String ownerDisplayName(String ownerId) {
        try {
            return userAccountRepository.findByEmail(ownerId.toLowerCase())
                    .map(UserAccountEntity::getDisplayName).orElse(ownerId);
        } catch (Exception e) {
            return ownerId;
        }
    }

    /**
     * Deterministic completed analysis for a closed demo case: the marker is
     * COMPLETED and a persisted run with a structured result exists — the same
     * coherent source of truth as a real pipeline run. The Entscheidungsvorlage
     * is therefore exportable even after the case advanced to Abschluss.
     */
    private void seedClosedCaseAnalysis(WorkspaceEntity ws) {
        try {
            attachCanonicalDocuments(ws);
            List<WorkspaceDocumentLinkEntity> links = workspaceService.getWorkspaceDocuments(ws.getId().toString());
            workspaceService.deleteAnalysisRuns(ws.getId().toString());
            int version = workspaceService.startAnalysisRun(ws.getId().toString(), ws.getOwnerId());
            Map<String, Object> result = fixtureResult(ws, links);
            List<String> evidenceIds = new ArrayList<>();
            for (WorkspaceDocumentLinkEntity link : links) {
                try {
                    Document doc = documentFacade.getDocument(UUID.fromString(link.getDocumentId()), "system");
                    evidenceIds.add(link.getDocumentId() + "@v" + doc.currentVersion());
                } catch (Exception e) {
                    evidenceIds.add(link.getDocumentId());
                }
            }
            java.util.Collections.sort(evidenceIds);
            workspaceService.completeAnalysisRun(ws.getId().toString(), version,
                    links.size(), evidenceIds, result);
            workspaceService.recordAnalysisStatus(ws.getId().toString(), "COMPLETED",
                    Map.of("sourceCount", links.size()));
            log.info("Demo-Fall '{}': abgeschlossene Analyse (v{}) hinterlegt, {} Quelle(n)",
                    ws.getName(), version, links.size());
        } catch (Exception e) {
            log.warn("Fixture-Analyse für '{}' fehlgeschlagen: {}", ws.getName(), e.getMessage());
        }
    }

    /** Attaches the canonical Ummeldung corpus documents (idempotent). */
    private void attachCanonicalDocuments(WorkspaceEntity ws) {
        List<WorkspaceDocumentLinkEntity> links = workspaceService.getWorkspaceDocuments(ws.getId().toString());
        Set<String> attached = links.stream()
                .map(WorkspaceDocumentLinkEntity::getDocumentId).collect(Collectors.toSet());
        for (String title : UMMELDUNG_DOCS) {
            try {
                var filter = new DocumentFilter(null, null, null, null, null, null, null, 0, 200);
                List<Document> candidates = documentFacade.findDocuments(filter).documents();
                for (Document doc : candidates) {
                    if (title.equalsIgnoreCase(doc.metadata().title())) {
                        if (!attached.contains(doc.id().toString())) {
                            DocumentCategory realType = parseCategory(doc.metadata().category());
                            workspaceService.attachDocument(new AttachDocumentCommand(
                                    ws.getId().toString(), doc.id().toString(), realType,
                                    doc.metadata().category() != null ? doc.metadata().category() : "general",
                                    null));
                            log.info("Korpus-Dokument '{}' an Demo-Fall '{}' angehängt", title, ws.getName());
                        }
                        return;
                    }
                }
                log.debug("Korpus-Dokument '{}' nicht gefunden", title);
            } catch (Exception e) {
                log.debug("Anhängen von '{}' fehlgeschlagen: {}", title, e.getMessage());
            }
        }
    }

    // ── Deterministic fixture result for closed cases ────────────────────────

    private Map<String, Object> fixtureResult(WorkspaceEntity ws, List<WorkspaceDocumentLinkEntity> links) {
        String name = ws.getName() != null ? ws.getName() : "Ummeldung";
        List<Map<String, Object>> evidence = new ArrayList<>();
        for (WorkspaceDocumentLinkEntity link : links) {
            try {
                Document doc = documentFacade.getDocument(UUID.fromString(link.getDocumentId()), "system");
                String title = doc.metadata() != null && doc.metadata().title() != null
                        ? doc.metadata().title() : link.getDocumentId();
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("documentId", link.getDocumentId());
                item.put("chunkId", null);
                item.put("documentVersion", doc.currentVersion());
                item.put("title", title);
                item.put("excerpt", excerptOf(doc.id()));
                item.put("confidence", "78%");
                item.put("confidenceRaw", 0.78);
                item.put("tier", "Primär");
                item.put("sourceType", "Faktisch");
                item.put("pageNumber", null);
                item.put("startOffset", null);
                item.put("endOffset", null);
                item.put("publishedAt", null);
                item.put("validFrom", null);
                item.put("validUntil", null);
                item.put("supersededAt", null);
                item.put("fillClass", "quality-indicator__fill--high");
                item.put("supportedBy", List.of());
                evidence.add(item);
            } catch (Exception e) {
                log.debug("Beleg-Auszug für '{}' nicht lesbar: {}", link.getDocumentId(), e.getMessage());
            }
        }

        List<Map<String, Object>> primary = new ArrayList<>();
        primary.add(finding("Wohnsitzanmeldung innerhalb der Frist erfolgt",
                "Die Anmeldung der neuen Wohnung wurde innerhalb von zwei Wochen nach dem Einzug vorgenommen.",
                List.of("Bundesmeldegesetz (BMG)", "Änderung/Wechsel der Hauptwohnung")));
        primary.add(finding("Angaben zur Person und Anschrift geprüft",
                "Die Angaben wurden anhand des vorgelegten Ausweisdokuments und der Wohnungsgeberbestätigung geprüft.",
                List.of("Wohnungsgeberbestätigung")));
        List<Map<String, Object>> secondary = new ArrayList<>();
        secondary.add(finding("Meldebestätigung ausgehändigt",
                "Die Meldebestätigung mit den gespeicherten Daten wurde der Bürgerin bzw. dem Bürger übergeben.",
                List.of()));
        List<Map<String, Object>> procedural = new ArrayList<>();
        procedural.add(finding("Meldebescheinigung für den Arbeitgeber anfordern (falls benötigt)",
                "Auf Wunsch wird eine Meldebescheinigung nach § 18 BMG ausgestellt.",
                List.of()));
        procedural.add(finding("Vorgang dokumentieren und abschließen",
                "Der Vorgang ist abgeschlossen und wird im Aktenbestand dokumentiert.",
                List.of()));

        Map<String, Object> confidence = new LinkedHashMap<>();
        confidence.put("sourceConfidence", 0.78);
        confidence.put("semanticConfidence", 0.74);
        confidence.put("structuralConfidence", 0.80);
        confidence.put("completenessConfidence", 0.70);
        confidence.put("overallConfidence", 0.76);
        confidence.put("explanation",
                "Die Angaben wurden anhand der vorgelegten Unterlagen geprüft; der Vorgang ist vollständig bearbeitet.");

        List<Map<String, Object>> authorities = new ArrayList<>();
        Map<String, Object> authority = new LinkedHashMap<>();
        authority.put("title", "Bundesmeldegesetz (BMG)");
        authority.put("reference", "§ 17 Abs. 1, § 19");
        authority.put("excerpt", "Die Anmeldung einer Wohnung ist innerhalb von zwei Wochen nach dem Einzug vorzunehmen.");
        authority.put("domain", "GENERAL");
        authority.put("basis", "Meldewesen");
        authority.put("relevance", "82%");
        authority.put("relevanceRaw", 0.82);
        authority.put("tier", "Primär");
        authority.put("fillClass", "quality-indicator__fill--high");
        authorities.add(authority);

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("caseId", ws.getId());
        result.put("caseName", name);
        result.put("analysisQuestion", "Analysiere den Fall \"" + name + "\".");
        result.put("asOf", LocalDate.now().toString());
        result.put("asOfDisplay", DateTimeFormatter.ofPattern("dd.MM.yyyy").format(LocalDate.now()));
        result.put("decisionAnswer", String.join("\n",
                "KURZANTWORT",
                "Die Ummeldung wurde vollständig bearbeitet. Die Anmeldung der neuen Wohnung ist fristgerecht erfolgt und die Meldebestätigung wurde ausgehändigt.",
                "",
                "ENTSCHEIDUNG",
                "Die Ummeldung wird nach § 17 Abs. 1 BMG als rechtzeitig angemeldet geführt. Der Vorgang ist abgeschlossen.",
                "",
                "RECHTSGRUNDLAGE",
                "- Bundesmeldegesetz (BMG), § 17 Abs. 1, § 19",
                "",
                "VERFAHREN",
                "Die Meldebestätigung wurde übergeben; die Datenweitergabe an beteiligte Stellen erfolgte gemäß BMG.",
                "",
                "NÄCHSTER SCHRITT",
                "Der Vorgang ist abgeschlossen und wird dokumentiert. Bei Rückfragen steht die zuständige Sachbearbeitung zur Verfügung."));
        result.put("grounded", true);
        result.put("model", "qwen2.5:7b");
        result.put("strategy", "Hybride Suche");
        result.put("requestedAt", DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm").format(LocalDateTime.now().minusMinutes(30)));
        result.put("completedAt", DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm").format(LocalDateTime.now()));
        result.put("confidenceScore", "76%");
        result.put("confidence", confidence);
        result.put("overallFillClass", "quality-indicator__fill--high");
        result.put("sourceFillClass", "quality-indicator__fill--high");
        result.put("completenessFillClass", "quality-indicator__fill--high");
        result.put("coverageFillClass", "quality-indicator__fill--high");
        result.put("evidenceItems", evidence);
        result.put("authorities", authorities);
        result.put("primaryFindings", primary);
        result.put("secondaryFindings", secondary);
        result.put("proceduralFindings", procedural);
        result.put("supportingFindings", List.of());
        result.put("findingRelationships", List.of());
        result.put("coverageScore", "76%");
        result.put("coverageScoreRaw", 0.76);
        result.put("presentRoles", List.of());
        result.put("missingRoles", List.of());
        result.put("missingDocs", List.of());
        result.put("assessmentNote", "Der Vorgang ist vollständig bearbeitet.");
        result.put("coverageIssues", List.of());
        result.put("analysisComplete", true);
        return result;
    }

    private Map<String, Object> finding(String label, String description, List<String> refs) {
        Map<String, Object> f = new LinkedHashMap<>();
        f.put("label", label);
        f.put("description", description);
        f.put("priority", "80%");
        f.put("priorityRaw", 0.8);
        f.put("role", "Kernfeststellung");
        f.put("fillClass", "quality-indicator__fill--high");
        f.put("governingRefs", refs);
        f.put("relatedRefs", List.of());
        f.put("evidenceLinks", List.of());
        return f;
    }

    private String excerptOf(UUID documentId) {
        try {
            List<DocumentChunkEntity> chunks = chunkRepository.findByDocumentIdOrderByChunkIndex(documentId);
            for (DocumentChunkEntity chunk : chunks) {
                String text = chunk.getText() != null ? chunk.getText().trim() : "";
                if (!text.isBlank()) {
                    return text.length() > 240 ? text.substring(0, 240) : text;
                }
            }
        } catch (Exception e) {
            log.debug("Chunk-Auszug für {} nicht lesbar: {}", documentId, e.getMessage());
        }
        return "Kein Auszug verfügbar.";
    }

    private static DocumentCategory parseCategory(String category) {
        if (category == null || category.isBlank()) return DocumentCategory.OTHER;
        try {
            return DocumentCategory.valueOf(category.trim().toUpperCase());
        } catch (IllegalArgumentException e) {
            return DocumentCategory.OTHER;
        }
    }

    private static String normalizeName(String name) {
        return name == null ? "" : name.toLowerCase().replace("-", "").replace("–", "").replace(" ", "");
    }

    private static String toJson(Map<String, Object> data) {
        try {
            return MAPPER.writeValueAsString(data);
        } catch (Exception e) {
            return "{}";
        }
    }
}
