package reasoning.common.audit;

/** Enumeration of all supported audit event types across auth, document, search, AI, and workflow domains. */
public enum AuditEventType {
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    USER_CREATED,
    USER_REGISTRATION_FAILED,
    TOKEN_REFRESHED,
    TOKEN_REFRESH_FAILED,
    ROLE_CHANGED,

    DOCUMENT_INGESTED,
    DOCUMENT_UPDATED,
    DOCUMENT_VIEWED,
    DOCUMENT_DELETED,

    SEARCH_EXECUTED,
    RETRIEVAL_EXECUTED,
    RERANKING_EXECUTED,

    MODEL_INFERENCE,
    PROMPT_EXECUTED,
    SUMMARY_GENERATED,
    CONTENT_EXTRACTION_EXECUTED,

    WORKFLOW_STARTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_FAILED,

    AGENT_TOOL_CALL,
    AGENT_WORKFLOW_STEP,

    PERMISSION_CHANGED,
    SECURITY_CONFIGURATION_CHANGED
}
