package reasoning.ai.analytics;

public enum RegressionType {
    RETRIEVAL_REGRESSION,
    VERIFICATION_REGRESSION,
    REPAIR_REGRESSION,
    LATENCY_REGRESSION,
    CONFIDENCE_REGRESSION,
    EVIDENCE_COVERAGE_REGRESSION,
    STAGE_FAILURE_REGRESSION,
    OUTCOME_REGRESSION
}
